# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  # trust the remote address because API Gateway has no fixed IP or CIDR range that we can target
  trusted_proxies: "127.0.0.1"
  # trust "X-Forwarded-*" headers coming from API Gateway
  trusted_headers: ["x-forwarded-for", "x-forwarded-proto", "x-forwarded-port"]
  secret: "%env(APP_SECRET)%"
  http_method_override: false
  handle_all_throwables: true
  profiler:
    enabled: false
    collect: false

  #esi: true
  #fragments: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
