framework:
  session:
    handler_id: App\Session\DynamoDbSessionHandler
    cookie_secure: true
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
  assets:
    base_urls: "%env(ASSET_URL)%"
