controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

assets:
    path: /assets/{path}
    controller: App\Controller\TestController::assets
    requirements:
        path: .+
